CUDA_VISIBLE_DEVICES=2,3 python main_RBNN.py \
--log_dir ./log_debug_rbnn \
--data_dir /mnt/nfsdisk/jier/4_MANN/mann_hdv/data \
--input_channel 1 \
--feature_dim 512 \
--class_num 5 \
--num_shot 1 \
--pool_query_train 10 \
--pool_val_train 3 \
--batch_size_train 4 \
--val_num_train 3 \
--pool_query_test 15 \
--batch_size_test 4 \
--train_episode 1000 \
--log_interval 100 \
--val_episode 250 \
--val_interval 200 \
--test_episode 1000 \
--learning_rate 0.0001 \
--quantization_learn RBNN \
--quantization_infer 1 \
--rotation_update 1 \
--a32 1 \
--test_only 0 \
--pretrained_dir None \
--sim_cal cos_softabs \
--binary_id 1 \
--gpu 2,3
